In [18]:
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import clear_output
import multiprocessing as mp

In [ ]:
import library
from importlib import reload
reload(library)

In [27]:
d = 10  # dimension of arms
K = 100  # number of arms
X = np.random.randn(K, d)  # arms

theta_star = np.random.randn(d)
idx_star = np.argmax(X@theta_star)  # index of best arm
x_star = X[idx_star]  # best arm

In [28]:
def A(X, lambda_):
    return X.T@np.diag(lambda_)@X

In [29]:
def gap(x, x_star=x_star):
    return (x_star - x) @ theta_star 

In [ ]:
Y_star = X - x_star

In [ ]:
(gap(x) @ theta_star) ** 2

In [30]:
V = np.eye(d)
B = np.matmul(X.reshape(-1,d,1), X.reshape(-1,1,d))

NameError: name 'self' is not defined

In [ ]:
np.argmax((x - x_star) @ () @ (x - x_star) / gap(x) ** 2)

In [ ]:
class XYStatic(object):

    def __init__(self, X, theta_star, T, sigma=1, name=""):
        self.X = X
        self.d = X.shape[1]
        self.sigma = sigma
        self.arm_sequence = []
        self.V = np.eye(self.d)
        self.theta_star = theta_star
        self.best_x = []
        self.name = name
        self.T = T

    def run(self, k):
        theta = np.zeros(self.d)
        S = 0
        for t in range(self.T):
            theta_hat = np.random.multivariate_normal(theta, np.linalg.inv(self.V))
            x_hat = 
            
            
            
            best_idx = np.argmax(self.X @ theta_hat)
            x_n = self.X[best_idx]
            y_n = x_n @ self.theta_star + self.sigma*np.random.randn()
            
            self.V += np.outer(x_n, x_n)
            S += x_n * y_n
            theta = np.linalg.inv(self.V) @ S         

## Scratch but don't delete

In [1]:
import numpy as np
l =[.1,.2,.3]
X = np.random.randn(3,2)
s = 0
for i in range(3):
    s += l[i]*np.outer(X[i], X[i])
print(s)

print(X.T@np.diag(l)@X)

[[0.21876108 0.21473142]
 [0.21473142 0.30097   ]]
[[0.21876108 0.21473142]
 [0.21473142 0.30097   ]]


In [ ]:
U = [u1, u2, u3]
V = [v1,v2,v3].T
U@v = u1@v1.T + u2@v2.T + u3@v3.T

In [8]:
d = 5
V = np.eye(d)
X = np.random.randn(20,d)


In [11]:
X = X.reshape(20,1,d)
XT = X.reshape(20,d,1)

In [25]:
A = V + np.matmul(XT,X)

In [27]:
x = np.random.randn(d)

In [28]:
x@A@x

array([ 3.13103687,  3.00954796,  5.05600226,  3.79457384,  2.85755611,
        3.110461  ,  8.68935298,  2.73731387,  3.07675707,  5.63451737,
        2.90532333,  5.35543615,  2.90781363,  3.80364324,  2.64713931,
       16.7744548 , 11.24417744,  2.90006682,  4.76877344,  3.99901224])

In [30]:
x@(V+np.outer(X[1],X[1]))@x

3.0095479645977257